export const STABILITY_THRESHOLD_MS = 1500
export const CRITICAL_THRESHOLD_MS = 3000
export const MISSED_PACKET_THRESHOLD_BUFFER_MS = 500
export const MIN_MISSED_PACKET_THRESHOLD_MS = 1500
export const ROLLING_AVG_HISTORY_LENGTH = 5
