// constants/workout.ts
export const WORKOUT_AUTO_START_HR_THRESHOLD_PERCENT = 70
export const WORKOUT_AUTO_START_DURATION_SECONDS = 5
export const WORKOUT_AUTO_START_COOLDOWN_SECONDS = 180
export const WORKOUT_AUTO_START_NOTIFICATION_DURATION_SECONDS = 10
