// .github/scripts/generate-release-notes.ts
import * as fs from 'fs'
import { generateReleaseNotes } from '../../services/geminiService'
import { GithubPullRequest } from '../../types/gemini'
import * as github from '@actions/github'
import * as core from '@actions/core'

const main = async () => {
  const token = process.env.GITHUB_TOKEN
  if (!token) {
    core.setFailed('GITHUB_TOKEN is not set')
    return
  }
  const octokit = github.getOctokit(token)

  const currentTagRef = process.env.GITHUB_REF?.replace('refs/tags/', '') || ''
  if (!currentTagRef) {
    core.setFailed('GITHUB_REF environment variable is not set.')
    return
  }

  const allTags = await octokit.paginate(octokit.rest.repos.listTags, {
    owner: github.context.repo.owner,
    repo: github.context.repo.repo,
    per_page: 100,
  })

  const sortedTags = allTags.sort((a, b) => {
    // This is a simple sort that should work for most versioning schemes.
    // For more complex cases, a proper semver library would be better.
    return a.name.localeCompare(b.name, undefined, { numeric: true })
  })

  const currentTagIndex = sortedTags.findIndex((t) => t.name === currentTagRef)
  if (currentTagIndex === -1) {
    core.setFailed(`Could not find current tag ${currentTagRef} in the list of tags.`)
    return
  }

  const previousTag = currentTagIndex > 0 ? sortedTags[currentTagIndex - 1] : null

  let previousTagDate: string
  if (previousTag) {
    const { data: previousTagObject } = await octokit.rest.git.getCommit({
      owner: github.context.repo.owner,
      repo: github.context.repo.repo,
      commit_sha: previousTag.commit.sha,
    });
    previousTagDate = previousTagObject.committer?.date || new Date(0).toISOString();
  } else {
    // Fallback for the first release
    const initialCommit = await octokit.paginate(octokit.rest.repos.listCommits, {
        owner: github.context.repo.owner,
        repo: github.context.repo.repo,
    });
    previousTagDate = initialCommit[initialCommit.length - 1].commit.committer?.date || new Date(0).toISOString();
  }


  const { data: currentTagObject } = await octokit.rest.git.getCommit({
    owner: github.context.repo.owner,
    repo: github.context.repo.repo,
    commit_sha: sortedTags[currentTagIndex].commit.sha,
  })

  const currentTagDate = currentTagObject.committer?.date || new Date().toISOString()


  core.info(
    `Generating release notes for ${currentTagRef} (since ${previousTag?.name || 'initial commit'})...`
  )

  const allMergedPrs = await octokit.paginate(octokit.rest.pulls.list, {
    owner: github.context.repo.owner,
    repo: github.context.repo.repo,
    state: 'closed',
    sort: 'updated',
    direction: 'desc',
    per_page: 100,
  })

  const relevantPrs = allMergedPrs.filter((pr) => {
    return (
      pr.merged_at &&
      new Date(pr.merged_at) > new Date(previousTagDate) &&
      new Date(pr.merged_at) <= new Date(currentTagDate)
    )
  })

  if (relevantPrs.length === 0) {
    core.info('No merged PRs found in this range.')
    fs.writeFileSync('release_notes.md', 'No significant changes found.')
    process.exit(0)
  }

  const prs: GithubPullRequest[] = relevantPrs.map((pr) => ({
    number: pr.number,
    title: pr.title,
    user: { login: pr.user?.login || '' },
    merged_at: pr.merged_at,
    body: pr.body || '',
    head: { ref: pr.head.ref },
    created_at: pr.created_at,
    draft: pr.draft || false,
    html_url: pr.html_url,
    state: 'merged',
    mergeable: null,
  }))

  try {
    const result = await generateReleaseNotes(prs, currentTagRef)
    const finalOutput = `${result.markdown}\n\n*Generated by Gemini Release Agent*`
    fs.writeFileSync('release_notes.md', finalOutput)
    core.info('✅ release_notes.md created successfully.')
  } catch (error) {
    if (error instanceof Error) {
      core.setFailed(`Error generating release notes: ${error.message}`)
    } else {
      core.setFailed('Unknown error generating release notes.')
    }
    process.exit(1)
  }
}

main()
