// .github/scripts/generate-release-notes.ts
import { execSync } from "child_process";
import * as fs from "fs";
import { generateReleaseNotes } from "../../services/geminiService";
import { GithubPullRequest } from "../../types/gemini";

const main = async () => {
  const currentTag = process.env.GITHUB_REF?.replace("refs/tags/", "") || "";
  if (!currentTag) {
    console.error("Error: GITHUB_REF environment variable is not set.");
    process.exit(1);
  }

  let previousTag = "";
  try {
    previousTag = execSync(`git describe --tags --abbrev=0 ${currentTag}^`).toString().trim();
  } catch (error) {
    console.warn("No previous tag found. Using the initial commit as the baseline.");
    if (error instanceof Error) {
      console.warn(`"git describe" failed with error: ${error.message}`);
    }
    previousTag = execSync("git rev-list --max-parents=0 HEAD").toString().trim();
  }

  console.log(`Generating release notes for ${currentTag} (since ${previousTag})...`);

  const logOutput = execSync(
    `git log ${previousTag}..${currentTag} --merges --pretty=format:"%H|%s|%an|%at|%b" --separator="END_COMMIT"`
  ).toString();

  const mergedPrs: GithubPullRequest[] = logOutput
    .split("END_COMMIT")
    .filter((s) => s.trim())
    .map((entry) => {
      const [hash, subject, author, timestamp, body] = entry.split("|");
      const prNumberMatch = subject.match(/#(\d+)/);
      return {
        number: prNumberMatch ? parseInt(prNumberMatch[1], 10) : 0,
        title: subject,
        user: { login: author },
        merged_at: new Date(parseInt(timestamp, 10) * 1000).toISOString(),
        body: body.trim(),
        head: { ref: "" }, // Not available from git log
        created_at: "", // Not available from git log
        draft: false, // Not available from git log
        html_url: "", // Not available from git log
        state: "closed", // Merged PRs are closed
        mergeable: null, // Not applicable
      };
    });

  if (mergedPrs.length === 0) {
    console.log("No merged PRs found in this range.");
    fs.writeFileSync("release_notes.md", "No significant changes found.");
    process.exit(0);
  }

  try {
    const result = await generateReleaseNotes(mergedPrs, currentTag);
    const finalOutput = `${result.markdown}\n\n*Generated by Gemini Release Agent*`;
    fs.writeFileSync("release_notes.md", finalOutput);
    console.log("✅ release_notes.md created successfully.");
  } catch (error) {
    console.error("Error generating release notes:", error);
    process.exit(1);
  }
};

main();
