// .github/scripts/release-notes-runner.ts
import { generateReleaseNotes } from '../../services/geminiService';
import { execSync } from 'child_process';
import * as fs from 'fs';

async function main() {
  const GITHUB_REF = process.env.GITHUB_REF || '';
  const currentTag = GITHUB_REF.replace('refs/tags/', '');
  let previousTag = '';

  try {
    previousTag = execSync(`git describe --tags --abbrev=0 ${currentTag}^ 2>/dev/null`)
      .toString()
      .trim();
  } catch (e) {
    console.log('No previous tag found. Using initial commit.');
    previousTag = execSync('git rev-list --max-parents=0 HEAD').toString().trim();
  }

  console.log(`Generating notes for ${currentTag} (since ${previousTag})...`);

  const logOutput = execSync(
    `git log ${previousTag}..${currentTag} --merges --pretty=format:"%H|%s|%b" --separator="END_COMMIT"`
  ).toString();

  const merges = logOutput.split('END_COMMIT').filter((s) => s.trim()).map((entry) => {
    const [hash, subject, body] = entry.split('|');
    const numberMatch = subject.match(/#(\d+)/);
    return {
      number: numberMatch ? parseInt(numberMatch[1], 10) : 0,
      title: subject,
      user: { login: '' },
      body: body ? body.trim() : '',
    };
  });

  if (merges.length === 0) {
    console.log('No merged PRs found in this range.');
    fs.writeFileSync('release_notes.md', 'No significant changes found.');
    process.exit(0);
  }

  const result = await generateReleaseNotes(merges as any, currentTag);
  const finalOutput = `${result.markdown}\n\n*Generated by Gemini Release Agent*`;
  fs.writeFileSync('release_notes.md', finalOutput);
  console.log('✅ release_notes.md created successfully.');
}

main().catch((error) => {
  console.error('Error generating release notes:', error);
  process.exit(1);
});
