// .github/scripts/release-notes-runner.ts
import { execSync } from 'child_process'
import * as fs from 'fs'
import { generateReleaseNotes } from '../../services/geminiService'
import { ReleaseNotePullRequestSummary } from '../../types'

const API_KEY = process.env.GEMINI_API_KEY
const GITHUB_REF = process.env.GITHUB_REF || '' // e.g., refs/tags/v1.0.0

if (!API_KEY) {
  console.error('Error: API_KEY environment variable is not set.')
  process.exit(1)
}

if (!GITHUB_REF.startsWith('refs/tags/')) {
  console.error('Error: This script should only be run on a tag push.')
  process.exit(0) // Exit gracefully
}

// 1. Determine Tag Range
const currentTag = GITHUB_REF.replace('refs/tags/', '')
let previousTag = ''

try {
  // Get the tag before the current one
  previousTag = execSync(
    `git describe --tags --abbrev=0 ${currentTag}^ 2>/dev/null`
  )
    .toString()
    .trim()
} catch (e) {
  console.log(
    'No previous tag found. Using the first commit as the starting point.'
  )
  try {
    // Fallback if this is the very first tag
    previousTag = execSync('git rev-list --max-parents=0 HEAD').toString().trim()
  } catch (revListError) {
    console.error(
      'Error: Failed to get initial commit. The repository might be empty.'
    )
    // If we can't find a start point, we can't proceed.
    process.exit(1)
  }
}

console.log(`Generating release notes for ${currentTag} (since ${previousTag})`)

// 2. Get Merged PRs using a single, efficient git log command
// This is much faster than running execSync for every commit.
// We use custom delimiters to make parsing reliable.
const DELIMITER = '<--FIELD-->'
const COMMIT_SEPARATOR = '<--EOC-->'
const logFormat = ['%s', '%an', '%cI', '%b'].join(DELIMITER)

const logOutput = execSync(
  `git log ${previousTag}..${currentTag} --merges --pretty=format:"${logFormat}${COMMIT_SEPARATOR}"`
).toString()

// TODO: This method of parsing PR numbers is brittle. It relies on the default
// GitHub merge commit message format ("Merge pull request #123..."). This will fail
// for squash merges or other customized merge strategies. A more robust solution
// would involve using the GitHub API to check which PRs are associated with the commits.
const merges: ReleaseNotePullRequestSummary[] = logOutput
  .split(COMMIT_SEPARATOR)
  .map(commit => {
    const [subject, author, mergedAt, body] = commit.split(DELIMITER)
    if (!subject || !subject.includes('Merge pull request #')) {
      return null
    }

    const prNumberMatch = subject.match(/#(\d+)/)
    if (!prNumberMatch) {
      return null
    }

    return {
      number: parseInt(prNumberMatch[1], 10),
      title: subject,
      user: { login: author ? author.trim() : 'unknown' },
      merged_at: mergedAt ? mergedAt.trim() : new Date().toISOString(),
      body: body ? body.trim() : '',
    }
  })
  .filter((pr): pr is ReleaseNotePullRequestSummary => pr !== null)

if (merges.length === 0) {
  console.log('No merged PRs found in this tag range.')
  fs.writeFileSync('release_notes.md', 'No new pull requests were merged.')
  process.exit(0)
}

console.log(`Found ${merges.length} merged PRs.`)

// 3. Call Gemini to Generate Notes
async function run() {
  try {
    console.log('Sending data to Gemini...')
    const result = await generateReleaseNotes(merges, currentTag)

    const finalOutput = `${result.markdown}\n\n*This changelog was generated by AI.*`
    fs.writeFileSync('release_notes.md', finalOutput)
    console.log('✅ Successfully created release_notes.md')
  } catch (error) {
    console.error('Error generating release notes:', error)
    fs.writeFileSync(
      'release_notes.md',
      'Error: Could not generate release notes.'
    )
    process.exit(1)
  }
}

run()
