services:
  hrm:
    build: .
    env_file:
      - .env.example
    environment:
      - REDIS_URL=redis://redis:6379
    ports:
      - '3000:3000'
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: pnpm run dev
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    ports:
      - '6379:6379'
