services:
  hrm:
    build: .
    env_file:
      - .env.example
    ports:
      - "${PORT:-3000}:${PORT:-3000}"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: pnpm run dev
