import { z } from 'zod'

/**
 * A unique identifier for a WebSocket client connection.
 * Generated by the server on initial connection.
 * @example "user-a1b2c3d4"
 */
export const ClientIdSchema = z
  .string()
  .regex(
    /^user-[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/,
    'Invalid Client ID format'
  )
  .brand<'ClientId'>()
export type ClientId = z.infer<typeof ClientIdSchema>

/**
 * A unique identifier for a Spotify playback device.
 * Provided by the Spotify Web API.
 * @example "a1b2c3d4e5f6g7h8i9j0k1l2m3n4o5p6q7r8s9t0"
 */
export const DeviceIdSchema = z.string().min(1).brand<'DeviceId'>()
export type DeviceId = z.infer<typeof DeviceIdSchema>
