// File: types/websocket.ts (Shared TypeScript Data Contracts)
/**
 * Defines the strict interfaces for all data passed between the server services
 * and the client hooks via the WebSocket connection.
 */
import { WebSocket } from 'ws'
import type {
  HrmStreamData as HrmData,
  TimerData,
  SpotifyPlaybackState as SpotifyData,
  TimerMode,
} from './core'

// --- WebSocket Connection & Augmentation ---

/**
 * Extends the base WebSocket type from the 'ws' library to include
 * application-specific properties for tracking client state, such as a
 * unique identifier and the last ping time for watchdog monitoring.
 */
export interface ExtWebSocket extends WebSocket {
  clientId: string
  isAlive: boolean
  clientType?: 'dashboard' | 'controller'
}

// --- Server Broadcast State Interfaces ---

export type { HrmData, TimerData, SpotifyData, TimerMode }

export type SpotifyCommand =
  | 'PLAY'
  | 'PAUSE'
  | 'NEXT'
  | 'PREVIOUS'
  | 'TRANSFER_PLAYBACK'
  | 'SET_VOLUME'
  | 'GET_DEVICES'

/**
 * The payload for the INITIAL_STATE message, representing the full application state.
 */
export interface InitialStateSnapshotPayload {
  hrmData: HrmData[]
  timerData: TimerData
  spotifyData: SpotifyData
  spotifyServiceInitialized?: boolean
}

/**
 * The portion of the state snapshot that is generated by the main server services,
 * excluding HRM data which is managed by the socket manager.
 */
export type StateSnapshot = Omit<InitialStateSnapshotPayload, 'hrmData'>

/**
 * The single, unified state object broadcast by the server to all clients.
 */
// TOPIC-BASED REAL-TIME MESSAGES
// Use a discriminated union for type-safe message handling
export interface ActiveAlert {
  clientId: string
  code: 'HRM_STALE' | 'BAD_PLACEMENT'
  message: string
  severity: 'warning' | 'error'
  timestamp: number
}

export type ServerMessage =
  | {
      type: 'INITIAL_STATE'
      payload: InitialStateSnapshotPayload
    }
  | { type: 'HRM_UPDATE'; payload: HrmData[] }
  | { type: 'TIMER_UPDATE'; payload: TimerData }
  | { type: 'SPOTIFY_UPDATE'; payload: SpotifyData }
  | { type: 'ACTIVE_ALERTS_UPDATE'; payload: ActiveAlert[] }
  | { type: 'SPOTIFY_SERVICE_INIT_UPDATE'; payload: boolean }
  | { type: 'PONG' } // Add PONG message type for server-to-client heartbeat
  | SpotifyExecutionMessage

/**
 * BroadcastData: a small, optional-shaped payload that services may send to
 * the socket broadcaster. This mirrors the ad-hoc interface previously found
 * inside the compiled `server.js` and centralizes it here for reuse.
 */

// --- Client Input Command Interfaces ---

export type HrmInputData = {
  value: number | null
}

export interface HrmInputMessage {
  type: 'HRM_INPUT'
  data: HrmInputData
}

export type HrmMetadataUpdateData = Omit<
  Partial<HrmData>,
  'clientId' | 'value' | 'calories'
>

export interface HrmMetadataUpdateMessage {
  type: 'HRM_METADATA_UPDATE'
  data: HrmMetadataUpdateData
}

export interface HrmStatsUpdateData {
  totalCalories: number
  hrZoneDurations: Record<number, number>
  hrHistory: { timestamp: number; hr: number }[]
}

export interface HrmStatsUpdateMessage {
  type: 'HRM_STATS_UPDATE'
  data: HrmStatsUpdateData
}

export interface TimerCommandMessage {
  type: 'TIMER_COMMAND'
  command: 'START' | 'PAUSE' | 'STOP'
}

export interface TimerModeCommandMessage {
  type: 'SET_MODE'
  mode: TimerMode
}

export interface TimerConfigMessage {
  type: 'TIMER_CONFIG'
  workDuration: number
  restDuration: number
}

export interface SpotifyCommandMessage {
  type: 'SPOTIFY_COMMAND'
  command: SpotifyCommand
  deviceId?: string | undefined
  volume?: number | undefined
  playlistUri?: string | undefined
}

export interface GetStateMessage {
  type: 'GET_STATE'
}

/**
 * Union type for all possible messages the client can send to the server.
 */
export interface ClientRegistrationMessage {
  type: 'REGISTER_CLIENT'
  role: 'dashboard' | 'controller'
}

export interface SpotifyExecutionMessage {
  type: 'EXECUTE_SPOTIFY'
  payload: SpotifyCommandMessage
}

export interface PingMessage {
  type: 'PING'
}

export type ClientCommandMessage =
  | HrmInputMessage
  | HrmMetadataUpdateMessage
  | HrmStatsUpdateMessage
  | TimerCommandMessage
  | TimerModeCommandMessage
  | SpotifyCommandMessage
  | TimerConfigMessage
  | GetStateMessage
  | ClientRegistrationMessage
  | PingMessage

import { z } from 'zod'

// --- Zod Schemas for Client Input Command Interfaces ---

export const HrmInputDataSchema = z.object({
  value: z.number().nullable(),
})

export const HrmInputMessageSchema = z.object({
  type: z.literal('HRM_INPUT'),
  data: HrmInputDataSchema,
})

export const HrmMetadataUpdateDataSchema = z.object({
  maxHr: z.number().optional(),
  name: z.string().optional(),
  age: z.number().optional(),
})

export const HrmMetadataUpdateMessageSchema = z.object({
  type: z.literal('HRM_METADATA_UPDATE'),
  data: HrmMetadataUpdateDataSchema,
})

export const HrmStatsUpdateDataSchema = z.object({
  totalCalories: z.number(),
  hrZoneDurations: z.record(z.string(), z.number()),
  hrHistory: z.array(z.object({ timestamp: z.number(), hr: z.number() })),
})

export const HrmStatsUpdateMessageSchema = z.object({
  type: z.literal('HRM_STATS_UPDATE'),
  data: HrmStatsUpdateDataSchema,
})

export const TimerCommandMessageSchema = z.object({
  type: z.literal('TIMER_COMMAND'),
  command: z.union([z.literal('START'), z.literal('PAUSE'), z.literal('STOP')]),
})

export const TimerModeCommandMessageSchema = z.object({
  type: z.literal('SET_MODE'),
  mode: z.union([z.literal('STOPWATCH'), z.literal('TABATA')]),
})

export const TimerConfigMessageSchema = z.object({
  type: z.literal('TIMER_CONFIG'),
  workDuration: z.number(),
  restDuration: z.number(),
})

export const SpotifyCommandMessageSchema = z.object({
  type: z.literal('SPOTIFY_COMMAND'),
  command: z.union([
    z.literal('PLAY'),
    z.literal('PAUSE'),
    z.literal('NEXT'),
    z.literal('PREVIOUS'),
    z.literal('TRANSFER_PLAYBACK'),
    z.literal('SET_VOLUME'),
    z.literal('GET_DEVICES'), // <--- ADDED
  ]),
  deviceId: z.string().optional(),
  volume: z.number().min(0).max(100).optional(),
  playlistUri: z.string().optional(),
})

export const GetStateMessageSchema = z.object({
  type: z.literal('GET_STATE'),
})

export const ClientRegistrationMessageSchema = z.object({
  type: z.literal('REGISTER_CLIENT'),
  role: z.union([z.literal('dashboard'), z.literal('controller')]),
})

export const PingMessageSchema = z.object({
  type: z.literal('PING'),
})

export const ClientCommandMessageSchema = z.discriminatedUnion('type', [
  HrmInputMessageSchema,
  HrmMetadataUpdateMessageSchema,
  HrmStatsUpdateMessageSchema,
  TimerCommandMessageSchema,
  TimerModeCommandMessageSchema,
  SpotifyCommandMessageSchema,
  TimerConfigMessageSchema,
  GetStateMessageSchema,
  ClientRegistrationMessageSchema,
  PingMessageSchema,
])
