// File: types/websocket.ts (Shared TypeScript Data Contracts)
/**
 * Defines the strict interfaces for all data passed between the server services
 * and the client hooks via the WebSocket connection.
 */
import { WebSocket } from 'ws'
import type {
  HrmStreamData as HrmData,
  TimerData,
  SpotifyPlaybackState as SpotifyData,
  TimerMode,
} from './core'

// --- WebSocket Connection & Augmentation ---

/**
 * Extends the base WebSocket type from the 'ws' library to include
 * application-specific properties for tracking client state, such as a
 * unique identifier and the last ping time for watchdog monitoring.
 */
export type SpotifyExecutionMessage = z.infer<typeof SpotifyCommandMessageSchema>;
export interface ExtWebSocket extends WebSocket {
  clientId: string
  isAlive: boolean
  clientType?: 'dashboard' | 'controller'
}

// --- Server Broadcast State Interfaces ---

export type { HrmData, TimerData, SpotifyData, TimerMode }

export type SpotifyCommand =
  | 'PLAY'
  | 'PAUSE'
  | 'NEXT'
  | 'PREVIOUS'
  | 'TRANSFER_PLAYBACK'
  | 'SET_VOLUME'
  | 'GET_DEVICES'

/**
 * The payload for the INITIAL_STATE message, representing the full application state.
 */
export interface InitialStateSnapshotPayload {
  hrmData: HrmData[]
  timerData: TimerData
  spotifyData: SpotifyData
  spotifyServiceInitialized?: boolean
}

/**
 * The portion of the state snapshot that is generated by the main server services,
 * excluding HRM data which is managed by the socket manager.
 */
export type StateSnapshot = Omit<InitialStateSnapshotPayload, 'hrmData'>

/**
 * The single, unified state object broadcast by the server to all clients.
 */
// TOPIC-BASED REAL-TIME MESSAGES
// Use a discriminated union for type-safe message handling
export interface ActiveAlert {
  clientId: string
  code: 'HRM_STALE' | 'BAD_PLACEMENT'
  message: string
  severity: 'warning' | 'error'
  timestamp: number
}

export type ServerMessage =
  | {
      type: 'INITIAL_STATE'
      payload: InitialStateSnapshotPayload
    }
  | { type: 'HRM_UPDATE'; payload: HrmData[] }
  | { type: 'TIMER_UPDATE'; payload: TimerData }
  | { type: 'SPOTIFY_UPDATE'; payload: SpotifyData }
  | { type: 'ACTIVE_ALERTS_UPDATE'; payload: ActiveAlert[] }
  | { type: 'SPOTIFY_SERVICE_INIT_UPDATE'; payload: boolean }
  | { type: 'PONG' } // Add PONG message type for server-to-client heartbeat
  | SpotifyExecutionMessage

/**
 * BroadcastData: a small, optional-shaped payload that services may send to
 * the socket broadcaster. This mirrors the ad-hoc interface previously found
 * inside the compiled `server.js` and centralizes it here for reuse.
 */

// --- Client Input Command Interfaces ---




import {
  HrmInputMessageSchema,
  HrmMetadataUpdateMessageSchema,
  TimerCommandMessageSchema,
  TimerModeCommandMessageSchema,
  SpotifyCommandMessageSchema,
  TimerConfigMessageSchema,
  GetStateMessageSchema,
  ClientRegistrationMessageSchema,
  PingMessageSchema,
  ClientCommandMessageSchema
} from '../lib/validation/schemas';
import { z } from 'zod';

export type HrmInputMessage = z.infer<typeof HrmInputMessageSchema>;
export type HrmMetadataUpdateMessage = z.infer<typeof HrmMetadataUpdateMessageSchema>;
export type TimerCommandMessage = z.infer<typeof TimerCommandMessageSchema>;
export type TimerModeCommandMessage = z.infer<typeof TimerModeCommandMessageSchema>;
export type SpotifyCommandMessage = z.infer<typeof SpotifyCommandMessageSchema>;
export type TimerConfigMessage = z.infer<typeof TimerConfigMessageSchema>;
export type GetStateMessage = z.infer<typeof GetStateMessageSchema>;
export type ClientRegistrationMessage = z.infer<typeof ClientRegistrationMessageSchema>;
export type PingMessage = z.infer<typeof PingMessageSchema>;
export type ClientCommandMessage = z.infer<typeof ClientCommandMessageSchema>;
