// File: types/websocket.ts (Shared TypeScript Data Contracts)
/**
 * Defines the strict interfaces for all data passed between the server services
 * and the client hooks via the WebSocket connection.
 */
import { WebSocket } from 'ws'
import { z } from 'zod'
import type {
  HrmStreamData as HrmData,
  TimerData,
  SpotifyPlaybackState as SpotifyData, // Single source of truth for playback state
  TimerMode,
  SpotifyCommand,
} from './core'

// --- WebSocket Connection & Augmentation ---

/**
 * Extends the base WebSocket type from the 'ws' library to include
 * application-specific properties for tracking client state, such as a
 * unique identifier and the last ping time for watchdog monitoring.
 */
export interface ExtWebSocket extends WebSocket {
  clientId: string
  isAlive: boolean
  clientType?: 'dashboard' | 'controller'
}

// --- Server Broadcast State Interfaces ---

export type { HrmData, TimerData, SpotifyData, SpotifyCommand }

/**
 * Represents HRM data stored in the client application state (e.g., Redux/Context).
 * Extends the raw server stream data with connection status and local timestamps.
 */
export interface ConnectedHrmData extends HrmData {
  isConnected: boolean
  lastUpdated?: number
}

/**
 * Represents the fully augmented HRM data used by UI components.
 * Includes derived state for staleness and alerts.
 */
export interface ClientHrmData extends ConnectedHrmData {
  isDataStale: boolean
  isAlerting: boolean
  alertMessage?: string
}

/**
 * The payload for the INITIAL_STATE message, representing the full application state.
 * hrmData is pre-filtered by the server (stale/generic/null entries removed).
 */
export interface InitialStateSnapshotPayload {
  hrmData: HrmData[]
  timerData: TimerData
  spotifyData: SpotifyData
  spotifyServiceInitialized?: boolean
}

/**
 * The portion of the state snapshot that is generated by the main server services,
 * excluding HRM data (which is managed and filtered by the socket manager).
 */
export type StateSnapshot = Omit<InitialStateSnapshotPayload, 'hrmData'>

/**
 * The single, unified state object broadcast by the server to all clients.
 */
// TOPIC-BASED REAL-TIME MESSAGES
// Use a discriminated union for type-safe message handling
export interface ActiveAlert {
  clientId: string
  code: 'HRM_STALE' | 'BAD_PLACEMENT'
  message: string
  severity: 'warning' | 'error'
  timestamp: number
}

export type ServerMessage = (
  | {
      type: 'INITIAL_STATE'
      payload: InitialStateSnapshotPayload
    }
  | {
      type: 'HRM_UPDATE'
      payload: HrmData[] // Filtered by the server before broadcast
    }
  | { type: 'TIMER_UPDATE'; payload: TimerData }
  | { type: 'SPOTIFY_UPDATE'; payload: SpotifyData }
  | { type: 'ACTIVE_ALERTS_UPDATE'; payload: ActiveAlert[] }
  | { type: 'SPOTIFY_SERVICE_INIT_UPDATE'; payload: boolean }
  | { type: 'PONG' } // Add PONG message type for server-to-client heartbeat
  | { type: 'DEVICE_OFFLINE'; payload: { deviceId: string } }
) & { serverTimestamp?: number }

/**
 * BroadcastData: a small, optional-shaped payload that services may send to
 * the socket broadcaster. This mirrors the ad-hoc interface previously found
 * inside the compiled `server.js` and centralizes it here for reuse.
 */

// --- Shared Zod Schemas ---

/**
 * Common HRM data fields shared between HRM_INPUT and HRM_METADATA_UPDATE.
 */
const HrmCommonDataSchema = z.object({
  maxHr: z.number().optional(),
  name: z.string().optional(),
  age: z.number().optional(),
})

// --- Client Input Command Interfaces ---

/**
 * Represents the data payload for an incoming HRM_INPUT message.
 * The `calories` field is optional to support older clients and handle
 * cases where the client has not yet calculated a value.
 */
const IncomingHrmDataSchema = HrmCommonDataSchema.extend({
  value: z.number().nullable(),
  calories: z.number().optional(),
  percentage: z.number().optional(),
  zone: z
    .enum([
      'ZONE_0',
      'ZONE_1',
      'ZONE_2',
      'ZONE_3',
      'ZONE_4',
      'ZONE_5',
      'ZONE_6',
    ])
    .optional(),
})

// Exported to support legacy consumers and maintain backward compatibility
export type IncomingHrmData = z.infer<typeof IncomingHrmDataSchema>

const HrmInputMessageSchema = z.object({
  type: z.literal('HRM_INPUT'),
  data: IncomingHrmDataSchema,
})

export type HrmInputMessage = z.infer<typeof HrmInputMessageSchema>

/**
 * Represents the data payload for an HRM_METADATA_UPDATE message.
 */
const HrmMetadataUpdateDataSchema = HrmCommonDataSchema.extend({
  weightKg: z.number().optional(),
  heightCm: z.number().optional(),
  weight: z.number().optional(),
  height: z.number().optional(),
  gender: z.enum(['MALE', 'FEMALE', 'NEUTRAL']).optional(),
})

export type HrmMetadataUpdateData = z.infer<typeof HrmMetadataUpdateDataSchema>

const HrmMetadataUpdateMessageSchema = z.object({
  type: z.literal('HRM_METADATA_UPDATE'),
  data: HrmMetadataUpdateDataSchema,
})

export type HrmMetadataUpdateMessage = z.infer<
  typeof HrmMetadataUpdateMessageSchema
>

export interface TimerCommandMessage {
  type: 'TIMER_COMMAND'
  command: 'START' | 'PAUSE' | 'STOP'
}

export interface TimerModeCommandMessage {
  type: 'SET_MODE'
  mode: TimerMode
}

export interface TimerConfigMessage {
  type: 'TIMER_CONFIG'
  workDuration: number
  restDuration: number
}

export interface SpotifyCommandMessage {
  type: 'SPOTIFY_COMMAND'
  command: SpotifyCommand
  deviceId?: string
  volume?: number
  playlistUri?: string // Added to support your incoming message
  contextUri?: string // Generic support for albums/artists
  uri?: string
  offset?: {
    position: number
  }
}

interface GetStateMessage {
  type: 'GET_STATE'
}

/**
 * Union type for all possible messages the client can send to the server.
 */
export interface ClientRegistrationMessage {
  type: 'REGISTER_CLIENT'
  role: 'dashboard' | 'controller'
}

interface PingMessage {
  type: 'PING'
}

export type ClientCommandMessage =
  | HrmInputMessage
  | HrmMetadataUpdateMessage
  | TimerCommandMessage
  | TimerModeCommandMessage
  | SpotifyCommandMessage
  | TimerConfigMessage
  | GetStateMessage
  | ClientRegistrationMessage
  | PingMessage

// --- Zod Schemas for Other Client Input Commands ---

const TimerCommandMessageSchema = z.object({
  type: z.literal('TIMER_COMMAND'),
  command: z.union([z.literal('START'), z.literal('PAUSE'), z.literal('STOP')]),
})

const TimerModeCommandMessageSchema = z.object({
  type: z.literal('SET_MODE'),
  mode: z.union([z.literal('STOPWATCH'), z.literal('TABATA')]),
})

const TimerConfigMessageSchema = z.object({
  type: z.literal('TIMER_CONFIG'),
  workDuration: z.number(),
  restDuration: z.number(),
})

const SpotifyCommandMessageSchema = z.object({
  type: z.literal('SPOTIFY_COMMAND'),
  command: z.union([
    z.literal('PLAY'),
    z.literal('PAUSE'),
    z.literal('NEXT'),
    z.literal('PREVIOUS'),
    z.literal('TRANSFER_PLAYBACK'),
    z.literal('SET_VOLUME'),
    z.literal('GET_DEVICES'),
  ]),
  deviceId: z.string().optional(),
  volume: z.number().min(0).max(100).optional(),
  playlistUri: z.string().optional(),
  contextUri: z.string().optional(),
  uri: z.string().optional(),
  offset: z
    .object({
      position: z.number(),
    })
    .optional(),
})

const GetStateMessageSchema = z.object({
  type: z.literal('GET_STATE'),
})

const ClientRegistrationMessageSchema = z.object({
  type: z.literal('REGISTER_CLIENT'),
  role: z.union([z.literal('dashboard'), z.literal('controller')]),
})

const PingMessageSchema = z.object({
  type: z.literal('PING'),
})

export const ClientCommandMessageSchema = z.discriminatedUnion('type', [
  HrmInputMessageSchema,
  HrmMetadataUpdateMessageSchema,
  TimerCommandMessageSchema,
  TimerModeCommandMessageSchema,
  SpotifyCommandMessageSchema,
  TimerConfigMessageSchema,
  GetStateMessageSchema,
  ClientRegistrationMessageSchema,
  PingMessageSchema,
])
