/**
 * @jest-environment node
 */
import { readFileSync } from 'fs'
import {
  run,
  IGitHubClient,
  SuggestedIssue,
  isDuplicate,
  ExistingIssue,
  GitHubClient, // Import the concrete class for testing
} from '../../../scripts/create-review-issues'
import { execSync } from 'child_process'

jest.mock('fs', () => ({
  readFileSync: jest.fn(),
  writeFileSync: jest.fn(),
  unlinkSync: jest.fn(),
}))

jest.mock('child_process', () => ({
  execSync: jest.fn(),
}))

const mockReadFileSync = readFileSync as jest.Mock
const mockExecSync = execSync as jest.Mock

// --- Mock GitHub Client ---

class MockGitHubClient implements IGitHubClient {
  public getOpenIssues = jest.fn()
  public createIssue = jest.fn()
}

describe('create-review-issues.ts', () => {
  let client: MockGitHubClient
  const MOCK_PR_NUMBER = '123'
  const MOCK_FILE_PATH = 'review_result.json'

  let consoleLogSpy: jest.SpyInstance
  let consoleErrorSpy: jest.SpyInstance
  let consoleWarnSpy: jest.SpyInstance

  beforeEach(() => {
    client = new MockGitHubClient()
    jest.clearAllMocks()

    // Spy on console methods
    consoleLogSpy = jest.spyOn(console, 'log').mockImplementation(() => {})
    consoleErrorSpy = jest.spyOn(console, 'error').mockImplementation(() => {})
    consoleWarnSpy = jest.spyOn(console, 'warn').mockImplementation(() => {})
  })

  afterEach(() => {
    consoleLogSpy.mockRestore()
    consoleErrorSpy.mockRestore()
    consoleWarnSpy.mockRestore()
  })

  const MOCK_VALID_REVIEW_RESULT = {
    reviewComment: 'LGTM!',
    labels: ['bug'],
    verdict: 'approve',
    prContext: {
      repo: 'test/repo',
      prNumber: '123',
      branchName: 'feature-branch',
      commitHash: 'abc1234',
    },
  }

  it('should create an issue when a valid suggestion is found', async () => {
    const issue: SuggestedIssue = {
      title: 'New Issue',
      description: 'A test issue',
      type: 'technical-debt',
      priority: 'medium',
    }
    mockReadFileSync.mockReturnValue(
      JSON.stringify({ ...MOCK_VALID_REVIEW_RESULT, suggestedIssues: [issue] })
    )
    client.getOpenIssues.mockReturnValue([])

    await run(client, MOCK_PR_NUMBER, MOCK_FILE_PATH)

    expect(client.getOpenIssues).toHaveBeenCalledWith('bot-generated')
    expect(client.createIssue).toHaveBeenCalledWith(
      issue,
      MOCK_VALID_REVIEW_RESULT.prContext
    )
    expect(consoleLogSpy).toHaveBeenCalledWith('Created: 1')
  })

  it('should skip a duplicate issue based on content hash', async () => {
    const issue: SuggestedIssue = {
      title: 'Duplicate Issue',
      description: 'This is a test.',
      type: 'bug',
      priority: 'high',
    }
    mockReadFileSync.mockReturnValue(
      JSON.stringify({ ...MOCK_VALID_REVIEW_RESULT, suggestedIssues: [issue] })
    )
    client.getOpenIssues.mockReturnValue([
      {
        title: 'Duplicate Issue',
        body: 'This is a test.\n\n---\n*Generated by Gemini Code Review*',
        number: 1,
        state: 'OPEN',
      },
    ])

    await run(client, MOCK_PR_NUMBER, MOCK_FILE_PATH)

    expect(client.createIssue).not.toHaveBeenCalled()
    expect(consoleLogSpy).toHaveBeenCalledWith(
      '⏭️  Skipping duplicate: "Duplicate Issue"'
    )
    expect(consoleLogSpy).toHaveBeenCalledWith('Skipped: 1')
  })

  it('should handle invalid review result JSON', async () => {
    mockReadFileSync.mockReturnValue('{"invalid json"}')
    await expect(run(client, MOCK_PR_NUMBER, MOCK_FILE_PATH)).rejects.toThrow(
      `❌ Error reading or parsing ${MOCK_FILE_PATH}: Expected ':' after property name in JSON at position 15 (line 1 column 16)`
    )
  })

  describe('isDuplicate', () => {
    it('should return true for identical issues', () => {
      const newIssue: SuggestedIssue = {
        title: 'Test',
        description: 'Body',
        type: 'bug',
        priority: 'high',
      }
      const existing: ExistingIssue[] = [
        {
          title: 'Test',
          body: 'Body',
          number: 1,
          state: 'OPEN',
        },
      ]
      expect(isDuplicate(newIssue, existing)).toBe(true)
    })
  })
})

describe('GitHubClient', () => {
  let client: GitHubClient

  beforeEach(() => {
    client = new GitHubClient()
    jest.clearAllMocks()
  })

  it('getOpenIssues should call gh cli with correct label filter', () => {
    mockExecSync.mockReturnValue('[]')
    client.getOpenIssues('bot-generated')
    expect(mockExecSync.mock.calls[0][0]).toContain('--label "bot-generated"')
  })

  it('createIssue should call gh cli with file paths', () => {
    const issue: SuggestedIssue = {
      title: 'File Path Test',
      description: 'Body here',
      type: 'bug',
      priority: 'low',
    }
    const context = { repo: 'a/b', prNumber: '1' }
    mockExecSync.mockReturnValue('https://github.com/a/b/issues/2')

    client.createIssue(issue, context)

    expect(mockExecSync.mock.calls[0][0]).toMatch(
      /gh issue create --title-file ".*" --body-file ".*" --label ".*"/
    )
  })

  it('getOpenIssues should handle invalid JSON from gh cli', () => {
    const consoleWarnSpy = jest.spyOn(console, 'warn').mockImplementation()
    mockExecSync.mockReturnValue('invalid json')
    const issues = client.getOpenIssues()
    expect(issues).toEqual([])
    expect(consoleWarnSpy).toHaveBeenCalled()
    consoleWarnSpy.mockRestore()
  })
})
