/**
 * @jest-environment node
 */

import { readFileSync } from 'fs'
import {
  run,
  IGitHubClient,
  SuggestedIssue,
  GitHubClient,
  isDuplicate,
  ExistingIssue,
} from '../../../scripts/create-review-issues'
import { execSync } from 'child_process'

// Mock the GitHubClient
class MockGitHubClient implements IGitHubClient {
  getOpenIssues = jest.fn().mockReturnValue([])
  createIssue = jest.fn()
}

// Mock fs.readFileSync
jest.mock('fs', () => ({
  ...jest.requireActual('fs'),
  readFileSync: jest.fn(),
}))

// Mock child_process.execSync
jest.mock('child_process', () => ({
  ...jest.requireActual('child_process'),
  execSync: jest.fn(),
}))

describe('create-review-issues script', () => {
  let client: MockGitHubClient
  const prNumber = '123'
  const reviewFilePath = 'review_result.json'

  beforeEach(() => {
    client = new MockGitHubClient()
    jest.clearAllMocks()
  })

  it('should run without crashing when there are no suggested issues', async () => {
    const reviewResult = {
      reviewComment: 'No issues found.',
      labels: [],
      verdict: 'approve',
      suggestedIssues: [],
    }
    ;(readFileSync as jest.Mock).mockReturnValue(JSON.stringify(reviewResult))

    await expect(run(client, prNumber, reviewFilePath)).resolves.not.toThrow()
    expect(client.getOpenIssues).not.toHaveBeenCalled()
    expect(client.createIssue).not.toHaveBeenCalled()
  })

  it('should create issues for all valid suggestions', async () => {
    const reviewResult = {
      reviewComment: 'Found some issues.',
      labels: [],
      verdict: 'comment',
      suggestedIssues: [
        {
          title: 'Refactor the authentication service',
          description: 'The auth service is too complex.',
          type: 'technical-debt',
          priority: 'high',
        },
        {
          title: 'Fix the button alignment',
          description: 'The button is not aligned correctly.',
          type: 'frontend-improvement',
          priority: 'low',
        },
      ],
    }
    ;(readFileSync as jest.Mock).mockReturnValue(JSON.stringify(reviewResult))

    await run(client, prNumber, reviewFilePath)

    expect(client.getOpenIssues).toHaveBeenCalledWith('bot-generated')
    expect(client.createIssue).toHaveBeenCalledTimes(2)
    expect(client.createIssue).toHaveBeenCalledWith(
      reviewResult.suggestedIssues[0],
      expect.any(Object)
    )
    expect(client.createIssue).toHaveBeenCalledWith(
      reviewResult.suggestedIssues[1],
      expect.any(Object)
    )
  })

  it('should skip duplicate issues', async () => {
    const reviewResult = {
      reviewComment: 'Found some issues.',
      labels: [],
      verdict: 'comment',
      suggestedIssues: [
        {
          title: 'Refactor the authentication service',
          description: 'The auth service is too complex.',
          type: 'technical-debt',
          priority: 'high',
        },
        {
          title: 'Fix the button alignment',
          description: 'The button is not aligned correctly.',
          type: 'frontend-improvement',
          priority: 'low',
        },
      ],
    }
    ;(readFileSync as jest.Mock).mockReturnValue(JSON.stringify(reviewResult))
    client.getOpenIssues.mockReturnValue([
      {
        number: 1,
        title: 'Refactor the authentication service',
        state: 'open',
        body: 'The auth service is too complex.\n\n---\n*Generated by Gemini Code Review*',
      },
    ])

    await run(client, prNumber, reviewFilePath)

    expect(client.getOpenIssues).toHaveBeenCalledWith('bot-generated')
    expect(client.createIssue).toHaveBeenCalledTimes(1)
    expect(client.createIssue).toHaveBeenCalledWith(
      reviewResult.suggestedIssues[1],
      expect.any(Object)
    )
  })

  describe('GitHubClient', () => {
    let ghClient: GitHubClient

    beforeEach(() => {
      ghClient = new GitHubClient()
    })

    it('should call gh issue create with the correct parameters', () => {
      const issue: SuggestedIssue = {
        title: 'Test Issue',
        description: 'Test Description',
        type: 'bug',
        priority: 'medium',
      }
      const context = {
        repo: 'test/repo',
        prNumber: '456',
        commitHash: 'abcdefg',
        branchName: 'test-branch',
      }

      // Create a more sophisticated mock for execSync
      ;(execSync as jest.Mock).mockImplementation((command: string) => {
        if (command.startsWith('gh label list')) {
          // Return an empty array for the label list to simulate no existing labels
          return '[]'
        }
        if (command.startsWith('gh issue create')) {
          // Return a URL for the issue creation
          return 'https://github.com/test/repo/issues/1'
        }
        // Return an empty string for any other command to avoid unexpected behavior
        return ''
      })

      ghClient.createIssue(issue, context)

      expect(execSync).toHaveBeenCalledWith(
        expect.stringContaining('gh issue create'),
        expect.any(Object)
      )
      expect(execSync).toHaveBeenCalledWith(
        expect.stringContaining(
          '--label "bot-generated,triage-needed,type-bug,priority-medium"'
        ),
        expect.any(Object)
      )
    })
  })

  describe('isDuplicate logic', () => {
    const newIssueBase: SuggestedIssue = {
      title: 'Test Issue',
      description: 'Test Description',
      type: 'technical-debt',
      priority: 'medium',
    }

    const existingIssueBase: ExistingIssue = {
      number: 1,
      title: 'Test Issue',
      state: 'open',
      body: 'Test Description',
    }

    it('should return true if fingerprints match', () => {
      const newIssue: SuggestedIssue = {
        ...newIssueBase,
        fingerprint: 'fingerprint-123',
      }
      const existingIssues: ExistingIssue[] = [
        {
          ...existingIssueBase,
          body: 'Some other description <!-- fingerprint: fingerprint-123 -->',
        },
      ]
      expect(isDuplicate(newIssue, existingIssues)).toBe(true)
    })

    it('should return false if fingerprints do not match and content is different', () => {
      const newIssue: SuggestedIssue = {
        ...newIssueBase,
        fingerprint: 'fingerprint-123',
      }
      const existingIssues: ExistingIssue[] = [
        {
          ...existingIssueBase,
          title: 'Different Title',
          body: 'Different Body <!-- fingerprint: fingerprint-456 -->',
        },
      ]
      expect(isDuplicate(newIssue, existingIssues)).toBe(false)
    })

    it('should return true if fingerprints mismatch but content signature matches', () => {
      const newIssue: SuggestedIssue = {
        ...newIssueBase,
        fingerprint: 'fingerprint-123',
      }
      const existingIssues: ExistingIssue[] = [
        {
          ...existingIssueBase,
          body: 'Test Description <!-- fingerprint: fingerprint-456 -->',
        },
      ]
      expect(isDuplicate(newIssue, existingIssues)).toBe(true)
    })

    it('should return true based on content signature when new issue has no fingerprint', () => {
      const newIssue: SuggestedIssue = { ...newIssueBase }
      const existingIssues: ExistingIssue[] = [
        {
          ...existingIssueBase,
          body: 'Test Description <!-- fingerprint: fingerprint-123 -->',
        },
      ]
      expect(isDuplicate(newIssue, existingIssues)).toBe(true)
    })

    it('should return true based on content signature when existing issue has no fingerprint', () => {
      const newIssue: SuggestedIssue = {
        ...newIssueBase,
        fingerprint: 'fingerprint-123',
      }
      const existingIssues: ExistingIssue[] = [{ ...existingIssueBase }]
      expect(isDuplicate(newIssue, existingIssues)).toBe(true)
    })

    it('should return true based on content signature when neither issue has a fingerprint', () => {
      const newIssue: SuggestedIssue = { ...newIssueBase }
      const existingIssues: ExistingIssue[] = [{ ...existingIssueBase }]
      expect(isDuplicate(newIssue, existingIssues)).toBe(true)
    })

    it('should return false when no fingerprint or signature matches', () => {
      const newIssue: SuggestedIssue = { ...newIssueBase }
      const existingIssues: ExistingIssue[] = [
        { ...existingIssueBase, title: 'A completely different title' },
      ]
      expect(isDuplicate(newIssue, existingIssues)).toBe(false)
    })

    it('should handle malformed fingerprint comments gracefully', () => {
      const newIssue: SuggestedIssue = {
        ...newIssueBase,
        fingerprint: 'fingerprint-123',
      }
      const existingIssues: ExistingIssue[] = [
        {
          ...existingIssueBase,
          title: 'A different title so signature fails',
          body: 'Test Description <!-- fingerprint:fingerprint-123 -->', // malformed
        },
      ]
      expect(isDuplicate(newIssue, existingIssues)).toBe(false)
    })
  })
})
