/**
 * @jest-environment node
 */
import { execSync } from 'child_process';
import { writeFileSync, unlinkSync } from 'fs';
import os from 'os';
import path from 'path';
import {
  isDuplicate,
  GitHubClient,
  type SuggestedIssue,
  type ExistingIssue,
} from '../../../scripts/create-review-issues';

// Mock external dependencies
jest.mock('child_process');
jest.mock('fs');
jest.mock('os', () => ({
    tmpdir: () => '/tmp',
}));

const mockedExecSync = execSync as jest.Mock;
const mockedWriteFileSync = writeFileSync as jest.Mock;
const mockedUnlinkSync = unlinkSync as jest.Mock;


describe('isDuplicate', () => {
  const newIssue: SuggestedIssue = {
    title: 'Refactor Authentication Logic',
    description: 'The authentication service is too complex.',
    type: 'technical-debt',
    priority: 'high',
  };

  const existingIssues: ExistingIssue[] = [
    {
      number: 1,
      title: 'Fix flaky test in UI',
      state: 'open',
      body: 'The login test fails intermittently.',
    },
    {
      number: 2,
      title: 'Refactor Authentication Logic',
      state: 'open',
      body: 'The authentication service is too complex.\n\n---\n*Generated by AI*',
    },
  ];

  it('should return true for an identical issue', () => {
    expect(isDuplicate(newIssue, existingIssues)).toBe(true);
  });

  it('should return false for a unique issue', () => {
    const uniqueIssue: SuggestedIssue = {
      ...newIssue,
      title: 'Implement new feature',
    };
    expect(isDuplicate(uniqueIssue, existingIssues)).toBe(false);
  });

  it('should return false when there are no existing issues', () => {
    expect(isDuplicate(newIssue, [])).toBe(false);
  });

  it('should correctly handle different footers in the issue body', () => {
    const slightlyDifferentNewIssue: SuggestedIssue = {
        ...newIssue,
        description: 'The authentication service is too complex.',
    };
    const existingIssueWithDifferentFooter: ExistingIssue[] = [{
        ...existingIssues[1],
        body: 'The authentication service is too complex.\n\n---\n*Different Footer*',
    }];
    expect(isDuplicate(slightlyDifferentNewIssue, existingIssueWithDifferentFooter)).toBe(true);
  });

  it('should return false if the description is different', () => {
    const differentDescriptionIssue: SuggestedIssue = {
        ...newIssue,
        description: 'A completely different description.',
    };
    expect(isDuplicate(differentDescriptionIssue, existingIssues)).toBe(false);
  });
});


describe('GitHubClient', () => {
  let client: GitHubClient;
  let consoleWarnSpy: jest.SpyInstance;

  beforeEach(() => {
    client = new GitHubClient();
    mockedExecSync.mockClear();
    mockedWriteFileSync.mockClear();
    mockedUnlinkSync.mockClear();
    consoleWarnSpy = jest.spyOn(console, 'warn').mockImplementation(() => {});
  });

  afterEach(() => {
    consoleWarnSpy.mockRestore();
  });

  describe('getOpenIssues', () => {
    it('should fetch and parse open issues', () => {
      const mockIssues: ExistingIssue[] = [{ number: 1, title: 'Test', state: 'open', body: '' }];
      mockedExecSync.mockReturnValue(JSON.stringify(mockIssues));
      const issues = client.getOpenIssues('bot-generated');
      expect(issues).toEqual(mockIssues);
      expect(mockedExecSync).toHaveBeenCalledWith(
        expect.stringContaining('--label "bot-generated"'),
        expect.any(Object)
      );
    });

    it('should return an empty array if gh command fails', () => {
      mockedExecSync.mockImplementation(() => { throw new Error('CLI error'); });
      const issues = client.getOpenIssues();
      expect(issues).toEqual([]);
      expect(consoleWarnSpy).toHaveBeenCalled();
    });

    it('should return an empty array for invalid JSON', () => {
      mockedExecSync.mockReturnValue('invalid json');
      const issues = client.getOpenIssues();
      expect(issues).toEqual([]);
      expect(consoleWarnSpy).toHaveBeenCalled();
    });
  });

  describe('createIssue', () => {
    const issue: SuggestedIssue = {
      title: 'New Issue',
      description: 'Issue Description',
      type: 'bug',
      priority: 'medium',
    };
    const context = { repo: 'test/repo', prNumber: '123', commitHash: 'abcdef' };

    it('should create an issue with the correct details', () => {
        mockedExecSync.mockReturnValue('https://github.com/test/repo/issues/1');
        client.createIssue(issue, context);

        expect(mockedWriteFileSync).toHaveBeenCalledTimes(2);

        const bodyContent = mockedWriteFileSync.mock.calls[1][1];
        expect(bodyContent).toContain(issue.description);
        expect(bodyContent).toContain('PR #123');
        expect(bodyContent).toContain('`abcdef`');

        expect(mockedExecSync).toHaveBeenCalledWith(
            expect.stringContaining('gh issue create'),
            expect.any(Object)
        );
        expect(mockedExecSync).toHaveBeenCalledWith(
            expect.stringContaining('--label "bot-generated,triage-needed,type-bug,priority-medium"'),
            expect.any(Object)
        );
        expect(mockedUnlinkSync).toHaveBeenCalledTimes(2);
    });

    it('should throw an error if the gh command fails', () => {
        mockedExecSync.mockImplementation(() => {
            throw new Error('Failed to create');
        });

        expect(() => {
            client.createIssue(issue, context);
        }).toThrow('GitHub CLI Error');
    });
  });
});
