import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'HRM | Real-Time Heart Rate Monitor',
  description: 'Generated by create next app',
}

export default function Head() {
  return (
    <>
      <title>{metadata.title as React.ReactNode}</title>
      <meta name="description" content={metadata.description as string} />
    </>
  )
}
