import type { Metadata } from 'next'
import { Inter, Roboto_Mono } from 'next/font/google'
import BottomNavBar from '../components/BottomNavBar' // Import the new component
import Providers from '../components/Providers'
import ThemeRegistry from '../components/ThemeRegistry/ThemeRegistry'
import ErrorBoundary from '../components/ErrorBoundary'
import ErrorFallback from '../components/ErrorFallback'
import TimerSoundProvider from '../components/TimerSoundProvider'
import { WebSocketProvider } from '../contexts/WebSocketContext'
import './globals.css'
const inter = Inter({
  subsets: ['latin'],
  variable: '--font-inter',
})

const roboto_mono = Roboto_Mono({
  subsets: ['latin'],
  variable: '--font-roboto-mono',
})

export const metadata: Metadata = {
  title: 'HRM Dashboard',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`${inter.variable} ${roboto_mono.variable}`}>
        {/* ThemeRegistry now contains all the logic */}
        <ThemeRegistry options={{ key: 'mui' }}>
          <Providers>
            <WebSocketProvider>
              <ErrorBoundary fallback={<ErrorFallback />}>
                <TimerSoundProvider>{children}</TimerSoundProvider>
              </ErrorBoundary>
            </WebSocketProvider>
          </Providers>
          <BottomNavBar />
        </ThemeRegistry>
      </body>
    </html>
  )
}
