import './globals.css'
import { Inter, Roboto_Mono } from 'next/font/google'
import MainLayout from './main'

const inter = Inter({
  subsets: ['latin'],
  variable: '--font-inter',
  display: 'swap',
})

const roboto_mono = Roboto_Mono({
  subsets: ['latin'],
  variable: '--font-roboto-mono',
  display: 'swap',
})

export const metadata = {
  title: 'HRM | Real-Time Heart Rate Monitor',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.variable} ${roboto_mono.variable}`}>
        <MainLayout>{children}</MainLayout>
      </body>
    </html>
  )
}
