import type { Metadata } from 'next'
import { Inter, Roboto_Mono } from 'next/font/google'
import Main from './main'
import ThemeProvider from '@/theme/theme'
import ThemeRegistry from '@/components/ThemeRegistry/ThemeRegistry'
import './globals.css'
const inter = Inter({
  subsets: ['latin'],
  variable: '--font-inter',
  display: 'swap',
})

const roboto_mono = Roboto_Mono({
  subsets: ['latin'],
  variable: '--font-roboto-mono',
  display: 'swap',
})

export const metadata: Metadata = {
  title: 'HRM | Real-Time Heart Rate Monitor',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <head>
        {/* Preload the primary display font to prevent FOUT. */}
        <link
          rel="preload"
          href="/assets/digital-7-mono.ttf"
          as="font"
          type="font/ttf"
          crossOrigin="anonymous"
        />
      </head>
      <body className={`${inter.variable} ${roboto_mono.variable}`}>
        <ThemeProvider>
          <ThemeRegistry options={{ key: 'mui' }}>
            <Main>{children}</Main>
          </ThemeRegistry>
        </ThemeProvider>
      </body>
    </html>
  )
}
