import type { Metadata } from 'next'
import RootLayout from './layout'

export const metadata: Metadata = {
  title: 'HRM | Real-Time Heart Rate Monitor',
  description: 'Generated by create next app',
}

export default function LayoutWrapper({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return <RootLayout>{children}</RootLayout>
}
