import {
  calculateJaccardSimilarity,
  isDuplicate,
  isLowQualityIssue,
  SuggestedIssue,
  ExistingIssue,
} from '../create-review-issues'

describe('create-review-issues logic', () => {
  describe('calculateJaccardSimilarity', () => {
    it('should return 1 for identical strings', () => {
      expect(calculateJaccardSimilarity('Hello World', 'Hello World')).toBe(1)
    })

    it('should return 0 for completely different strings', () => {
      expect(calculateJaccardSimilarity('Apple Orange', 'Banana Grape')).toBe(0)
    })

    it('should handle fuzzy matches', () => {
      const s1 = 'Refactor auth service for better performance'
      const s2 = 'Refactor auth service to improve performance'
      const similarity = calculateJaccardSimilarity(s1, s2)
      expect(similarity).toBeGreaterThan(0.5)
      expect(similarity).toBeLessThan(1)
    })

    it('should normalize strings (case and punctuation)', () => {
      expect(
        calculateJaccardSimilarity('Hello, World!', 'hello world')
      ).toBe(1)
    })

    it('should ignore short words', () => {
      expect(calculateJaccardSimilarity('a the to in', 'of by at')).toBe(1) // Both sets empty after filter
    })
  })

  describe('isDuplicate', () => {
    const existingIssues: ExistingIssue[] = [
      {
        number: 1,
        title: 'Original Issue',
        state: 'open',
        body: 'Description here.\n\n---\n*Generated by Gemini Code Review*\n- **Source:** PR #1\n<!-- fingerprint: auth:validate -->',
      },
      {
        number: 2,
        title: 'Fuzzy Match Title',
        state: 'closed',
        body: 'Different description.\n\n---\n*Generated by Gemini Code Review*',
      },
    ]

    it('should detect duplicate via fingerprint', () => {
      const newIssue: SuggestedIssue = {
        title: 'New Title',
        description: 'New Description',
        type: 'technical-debt',
        priority: 'medium',
        fingerprint: 'auth:validate',
      }
      expect(isDuplicate(newIssue, existingIssues)).toBe(true)
    })

    it('should detect duplicate via fuzzy title match', () => {
      const newIssue: SuggestedIssue = {
        title: 'Fuzzy Match Title!', // Near identical to issue #2
        description: 'New Description',
        type: 'technical-debt',
        priority: 'medium',
      }
      expect(isDuplicate(newIssue, existingIssues)).toBe(true)
    })

    it('should detect duplicate via exact content match (legacy)', () => {
      const newIssue: SuggestedIssue = {
        title: 'Original Issue',
        description: 'Description here.',
        type: 'technical-debt',
        priority: 'medium',
      }
      expect(isDuplicate(newIssue, existingIssues)).toBe(true)
    })

    it('should not detect duplicate for different issues', () => {
      const newIssue: SuggestedIssue = {
        title: 'Completely New Issue',
        description: 'Unique description here.',
        type: 'bug',
        priority: 'high',
        fingerprint: 'unique:fingerprint',
      }
      expect(isDuplicate(newIssue, existingIssues)).toBe(false)
    })
  })

  describe('isLowQualityIssue', () => {
    it('should reject short descriptions', () => {
      const issue: SuggestedIssue = {
        title: 'Valid Title',
        description: 'Too short.',
        type: 'bug',
        priority: 'low',
      }
      expect(isLowQualityIssue(issue, null)).toBe(true)
    })

    it('should reject generic titles', () => {
      const issue: SuggestedIssue = {
        title: 'Refactor code',
        description: 'This is a long enough description that should be valid otherwise.',
        type: 'technical-debt',
        priority: 'low',
      }
      expect(isLowQualityIssue(issue, null)).toBe(true)
    })

    it('should reject "AI slop" via pattern', () => {
      const slopPattern = /delve|seamless/i
      const issue: SuggestedIssue = {
        title: 'Issue title with "seamless" keyword',
        description: 'Issue description containing the word "delve".',
        type: 'technical-debt',
        priority: 'low',
      }
      expect(isLowQualityIssue(issue, slopPattern)).toBe(true)
    })

    it('should accept high quality issues', () => {
      const issue: SuggestedIssue = {
        title: 'Fix Race Condition in Auth Flow',
        description: 'The validateToken function has a race condition when multiple requests arrive simultaneously.',
        type: 'bug',
        priority: 'high',
      }
      expect(isLowQualityIssue(issue, null)).toBe(false)
    })
  })
})
