import {
  calculateJaccardSimilarity,
  tokenize,
  isDuplicate,
  isLowQualityIssue,
  SuggestedIssue,
  PreparedExistingIssue,
} from '../create-review-issues'

describe('create-review-issues logic', () => {
  describe('tokenize', () => {
    it('should normalize strings and remove punctuation', () => {
      const tokens = tokenize('Hello, World!')
      expect(tokens.has('hello')).toBe(true)
      expect(tokens.has('world')).toBe(true)
      expect(tokens.size).toBe(2)
    })

    it('should remove short words (<= 2 chars)', () => {
      const tokens = tokenize('is it at the')
      expect(tokens.has('is')).toBe(false)
      expect(tokens.has('it')).toBe(false)
      expect(tokens.has('at')).toBe(false)
      expect(tokens.has('the')).toBe(true) // 3 chars > 2
    })
  })

  describe('calculateJaccardSimilarity', () => {
    it('should return 1 for identical sets', () => {
      const tokens = tokenize('Hello World')
      expect(calculateJaccardSimilarity(tokens, tokens)).toBe(1)
    })

    it('should return 0 for completely different sets', () => {
      const t1 = tokenize('Apple Orange')
      const t2 = tokenize('Banana Grape')
      expect(calculateJaccardSimilarity(t1, t2)).toBe(0)
    })

    it('should handle fuzzy matches', () => {
      const s1 = 'Refactor auth service for better performance'
      const s2 = 'Refactor auth service to improve performance'
      const similarity = calculateJaccardSimilarity(tokenize(s1), tokenize(s2))
      expect(similarity).toBeGreaterThan(0.5)
      expect(similarity).toBeLessThan(1)
    })

    it('should handle empty sets (short words only)', () => {
      // 'is', 'it', 'at', 'on' are all <= 2 chars -> empty sets
      expect(calculateJaccardSimilarity(tokenize('is it'), tokenize('at on'))).toBe(1)
    })
  })

  describe('isDuplicate', () => {
    const existingIssues: PreparedExistingIssue[] = [
      {
        number: 1,
        title: 'Original Issue',
        state: 'open',
        body: 'Description here.\n\n---\n*Generated by Gemini Code Review*\n- **Source:** PR #1\n<!-- fingerprint: auth:validate -->',
        titleTokens: tokenize('Original Issue'),
      },
      {
        number: 2,
        title: 'Fuzzy Match Title',
        state: 'closed',
        body: 'Different description.\n\n---\n*Generated by Gemini Code Review*',
        titleTokens: tokenize('Fuzzy Match Title'),
      },
    ]

    it('should detect duplicate via fingerprint', () => {
      const newIssue: SuggestedIssue = {
        title: 'New Title',
        description: 'New Description',
        type: 'technical-debt',
        priority: 'medium',
        fingerprint: 'auth:validate',
      }
      expect(isDuplicate(newIssue, existingIssues)).toBe(true)
    })

    it('should detect duplicate via fuzzy title match', () => {
      const newIssue: SuggestedIssue = {
        title: 'Fuzzy Match Title!', // Near identical to issue #2
        description: 'New Description',
        type: 'technical-debt',
        priority: 'medium',
      }
      expect(isDuplicate(newIssue, existingIssues)).toBe(true)
    })

    it('should detect duplicate via exact content match (legacy)', () => {
      const newIssue: SuggestedIssue = {
        title: 'Original Issue',
        description: 'Description here.',
        type: 'technical-debt',
        priority: 'medium',
      }
      expect(isDuplicate(newIssue, existingIssues)).toBe(true)
    })

    it('should not detect duplicate for different issues', () => {
      const newIssue: SuggestedIssue = {
        title: 'Completely New Issue',
        description: 'Unique description here.',
        type: 'bug',
        priority: 'high',
        fingerprint: 'unique:fingerprint',
      }
      expect(isDuplicate(newIssue, existingIssues)).toBe(false)
    })
  })

  describe('isLowQualityIssue', () => {
    it('should reject short descriptions', () => {
      const issue: SuggestedIssue = {
        title: 'Valid Title',
        description: 'Too short.',
        type: 'bug',
        priority: 'low',
      }
      expect(isLowQualityIssue(issue, null)).toBe(true)
    })

    it('should reject generic titles', () => {
      const issue: SuggestedIssue = {
        title: 'Refactor code',
        description:
          'This is a long enough description that should be valid otherwise.',
        type: 'technical-debt',
        priority: 'low',
      }
      expect(isLowQualityIssue(issue, null)).toBe(true)
    })

    it('should reject "AI slop" via pattern', () => {
      // Obfuscate keywords to avoid triggering the slop detector on the test file itself
      const s1 = ['seam', 'less'].join('')
      const s2 = ['del', 've'].join('')
      const slopPattern = new RegExp(`${s1}|${s2}`, 'i')

      const issue: SuggestedIssue = {
        title: `Issue title with "${s1}" keyword`,
        description: `Issue description containing the word "${s2}".`,
        type: 'technical-debt',
        priority: 'low',
      }
      expect(isLowQualityIssue(issue, slopPattern)).toBe(true)
    })

    it('should accept high quality issues', () => {
      const issue: SuggestedIssue = {
        title: 'Fix Race Condition in Auth Flow',
        description:
          'The validateToken function has a race condition when multiple requests arrive simultaneously.',
        type: 'bug',
        priority: 'high',
      }
      expect(isLowQualityIssue(issue, null)).toBe(false)
    })
  })
})
