import { execSync } from 'child_process'
import { readFileSync, writeFileSync, unlinkSync } from 'fs'
import path from 'path'
import os from 'os'
import crypto from 'crypto'
import { z } from 'zod'

// --- Zod Schemas for Validation ---

const SuggestedIssueSchema = z.object({
  title: z.string(),
  description: z.string(),
  type: z.enum(['technical-debt', 'frontend-improvement', 'security', 'bug']),
  priority: z.enum(['high', 'medium', 'low']),
})

const PRContextSchema = z.object({
  repo: z.string().optional(),
  prNumber: z.string().optional(),
  branchName: z.string().optional(),
  commitHash: z.string().optional(),
})

const ReviewResultSchema = z.object({
  reviewComment: z.string(),
  labels: z.array(z.string()),
  verdict: z.string(),
  suggestedIssues: z.array(SuggestedIssueSchema).optional(),
  prContext: PRContextSchema.optional(),
})

const ExistingIssueSchema = z.object({
  number: z.number(),
  title: z.string(),
  state: z.string(),
  body: z.string(),
})

const ExistingIssuesSchema = z.array(ExistingIssueSchema)

// --- Types inferred from Zod ---

export type SuggestedIssue = z.infer<typeof SuggestedIssueSchema>
export type ReviewResult = z.infer<typeof ReviewResultSchema>
export type ExistingIssue = z.infer<typeof ExistingIssueSchema>

// --- GitHub Client Abstraction ---

export interface IGitHubClient {
  getOpenIssues(labelFilter?: string): ExistingIssue[]
  createIssue(
    issue: SuggestedIssue,
    context: z.infer<typeof PRContextSchema>
  ): void
}

export class GitHubClient implements IGitHubClient {
  private execute(command: string): string {
    try {
      return execSync(command, { encoding: 'utf-8', stdio: ['pipe', 'pipe', 'pipe'] }).trim()
    } catch (error: any) {
      const stderr = error.stderr ? error.stderr.toString() : 'Unknown error'
      throw new Error(`GitHub CLI Error: ${stderr}`)
    }
  }

  getOpenIssues(labelFilter?: string): ExistingIssue[] {
    console.log('🔍 Fetching existing issues to prevent duplicates...')
    let cmd = `gh issue list --state open --json number,title,state,body --limit 100`
    if (labelFilter) {
      cmd += ` --label "${labelFilter}"`
    }

    let output = ''
    try {
      output = this.execute(cmd)
      const parsed = JSON.parse(output)
      const validationResult = ExistingIssuesSchema.safeParse(parsed)
      if (!validationResult.success) {
        console.warn(
          `Warning: Invalid format for existing issues.`,
          validationResult.error
        )
        return []
      }
      return validationResult.data
    } catch (e) {
      const errorMessage = e instanceof Error ? e.message : 'Unknown error'
      console.warn(
        `Warning: Failed to fetch or parse existing issues. Duplicate detection might fail.
        Error: ${errorMessage}
        Raw GH CLI output:
        ${output}`
      )
      return []
    }
  }

  createIssue(
    issue: SuggestedIssue,
    context: z.infer<typeof PRContextSchema>
  ): void {
    const labels = [
      'bot-generated',
      'triage-needed',
      `type-${issue.type}`,
      `priority-${issue.priority}`,
    ].join(',')

    // PR Link Construction
    const prLink = context.repo
      ? `[PR #${context.prNumber}](https://github.com/${context.repo}/pull/${context.prNumber})`
      : `PR #${context.prNumber}`

    const commitLink =
      context.repo && context.commitHash
        ? `[\`${context.commitHash.substring(0, 7)}\`](https://github.com/${
            context.repo
          }/pull/${context.prNumber}/commits/${context.commitHash})`
        : context.commitHash
          ? `\`${context.commitHash.substring(0, 7)}\``
          : 'N/A'

    const branchInfo = context.branchName ? `\`${context.branchName}\`` : 'N/A'

    const footer = `
---
*Generated by Gemini Code Review*
- **Source:** ${prLink}
- **Branch:** ${branchInfo}
- **Commit:** ${commitLink}`

    const body = `${issue.description}${footer}`
    const title = issue.title

    console.log(`🚀 Creating issue: "${title}"...`)

    const tempDir = os.tmpdir()
    const titleFile = path.join(tempDir, `issue_title_${Date.now()}.txt`)
    const bodyFile = path.join(tempDir, `issue_body_${Date.now()}.md`)

    try {
      writeFileSync(titleFile, title, 'utf-8')
      writeFileSync(bodyFile, body, 'utf-8')

      const cmd = `gh issue create --title-file "${titleFile}" --body-file "${bodyFile}" --label "${labels}"`
      const url = this.execute(cmd)
      console.log(`✅ Issue created: ${url}`)
    } finally {
      unlinkSync(titleFile)
      unlinkSync(bodyFile)
    }
  }
}

// --- Deduplication ---

function getIssueSignature(title: string, description: string): string {
  const content = `${title.trim()}${description.trim()}`
  return crypto.createHash('sha256').update(content).digest('hex')
}

export function isDuplicate(
  newIssue: SuggestedIssue,
  existingIssues: ExistingIssue[]
): boolean {
  const newSignature = getIssueSignature(newIssue.title, newIssue.description)
  for (const existing of existingIssues) {
    // Strip the footer from the existing issue body before generating the signature
    const existingDescription = existing.body.split('\n\n---')[0] || ''
    const existingSignature = getIssueSignature(
      existing.title,
      existingDescription
    )
    if (newSignature === existingSignature) {
      return true
    }
  }
  return false
}

// --- Core Logic ---

export async function run(client: IGitHubClient, prNumber: string, reviewFilePath: string) {
  if (!prNumber) {
    console.error('❌ Error: PR_NUMBER is missing.')
    return
  }

  let result: ReviewResult
  try {
    const content = readFileSync(path.resolve(process.cwd(), reviewFilePath), 'utf-8')
    const parsedJson = JSON.parse(content)
    const validationResult = ReviewResultSchema.safeParse(parsedJson)
    if (!validationResult.success) {
      console.error(
        `❌ Error validating ${reviewFilePath}:`,
        validationResult.error
      )
      return
    }
    result = validationResult.data
  } catch (e) {
    console.error(
      `❌ Error reading or parsing ${reviewFilePath}: ${(e as Error).message}`
    )
    return
  }

  if (!result.suggestedIssues || result.suggestedIssues.length === 0) {
    console.log('✨ No suggested issues found in the review result.')
    return
  }

  const existingIssues = client.getOpenIssues('bot-generated')

  let createdCount = 0
  let skippedCount = 0

  for (const issue of result.suggestedIssues) {
    if (isDuplicate(issue, existingIssues)) {
      console.log(`⏭️  Skipping duplicate: "${issue.title}"`)
      skippedCount++
      continue
    }

    // Fallback context if not present in the review file
    const context = result.prContext ?? {
      repo: process.env.GITHUB_REPOSITORY,
      prNumber: prNumber,
    }

    client.createIssue(issue, context)
    createdCount++
  }

  console.log(`\n--- Summary ---`)
  console.log(`Created: ${createdCount}`)
  console.log(`Skipped: ${skippedCount}`)
}


// --- Main Execution ---

// istanbul ignore next
if (require.main === module) {
  const client = new GitHubClient()
  const prNumber = process.env.PR_NUMBER
  const reviewFile = 'review_result.json'

  run(client, prNumber || '', reviewFile).catch(err => {
    console.error('Unhandled error:', err)
    process.exit(1)
  })
}
