name: 'GH PR Wait Checks'
description: 'Waits for PR checks to complete'
inputs:
  pr_number:
    description: 'PR number'
    required: true
  timeout:
    description: 'Timeout in seconds'
    required: false
    default: '300'
runs:
  using: 'composite'
  steps:
    - shell: bash
      run: |
        timeout ${{ inputs.timeout }} gh pr checks ${{ inputs.pr_number }} --watch
