name: 'GH PR Close'
description: 'Closes a Pull Request'
inputs:
  pr_number:
    description: 'PR number'
    required: true
  github_token:
    description: 'GitHub token for authentication'
    required: true
runs:
  using: 'composite'
  steps:
    - shell: bash
      env:
        GH_TOKEN: ${{ inputs.github_token }}
      run: |
        set -e
        gh pr close ${{ inputs.pr_number }}
