# Use the generic runner image as the base
FROM hrm-actions-runner-generic:latest

# Install Playwright System Dependencies
# We install these now so the runner is ready for 'npm run test:visual' immediately
# We temporarily use a dummy project to invoke install-deps
RUN cd /home/runner && \
    npm init -y && \
    npm install @playwright/test@1.56.1 && \
    npx playwright install-deps && \
    rm -rf package.json package-lock.json node_modules
