name: Auto Rebase

on:
  push:
    branches:
      - main
  # Allows manual triggering from the Actions tab
  workflow_dispatch:

jobs:
  rebase:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Rebase PRs
        uses: peter-evans/rebase@v3
        with:
          token: ${{ secrets.PAT_TOKEN }} # Use a PAT to ensure CI workflows trigger after rebase
          base: main
          # "Intelligent" behavior: Exclude branches with specific labels (e.g., if you are in the middle of a complex refactor)
          exclude-labels: |
            no-rebase
            wip
