name: Auto Rebase

on:
  push:
    branches:
      - leader
  workflow_dispatch:

jobs:
  rebase:
    runs-on: self-hosted
    steps:
      - name: 'Setup Environment'
        uses: ./.github/actions/setup-env
        with:
          fetch-depth: 0

      - name: Rebase PRs
        uses: peter-evans/rebase@v3
        with:
          token: ${{ secrets.PAT_TOKEN }}
          base: leader
          exclude-labels: |
            no-rebase
            wip
