name: Lint Commit Messages
on: [pull_request]

permissions:
  pull-requests: write

jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: wagoid/commitlint-github-action@v6
      - name: Post Comment on Failure
        if: failure() && (github.event.pull_request && github.event.pull_request.number && github.event.pull_request.number != 0)
        uses: peter-evans/create-or-update-comment@v4
        with:
          issue-number: ${{ (github.event.pull_request && github.event.pull_request.number) || 0 }}
          body: |
            :no_entry: **Commit Message Linting Failed**

            One or more of your commit messages do not follow the project's conventions.
            Please review the [commitlint logs](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}) for more details.

            You can also refer to the [commit message guidelines](https://github.com/conventional-changelog/commitlint/#what-is-commitlint) for help.

  pr-title-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: pnpm install @commitlint/cli @commitlint/config-conventional
      - name: Lint PR title
        if: github.event.pull_request
        run: echo "${{ (github.event.pull_request && github.event.pull_request.title) || '' }}" | pnpm exec commitlint --config commitlint.config.cjs
