name: Release

on:
  # This workflow is triggered on pushes to the 'leader' branch.
  # The release-please-action creates a "Release PR". When this PR is merged,
  # it constitutes a push to 'leader', which then triggers the action to create
  # the actual GitHub Release and tag.
  push:
    branches:
      - leader

jobs:
  release:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Release Please
        uses: googleapis/release-please-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: node
